# animate FUTURES output

t.create output=futures_series type=strds temporaltype=relative \
    semantictype=mean title="Development" \
    description="Development time series 2008 to 2035 generated by FUTURES"

# g.list type=raster pattern=step_*

# t.register input=futures_series file=D:\Raleigh_Prototype_Zoning\scripts\FUTURES\animation_list.txt start=2008 unit=years increment=1
t.register input=futures_series file=animation.txt start=2008 unit=years increment=1

t.info futures_series
t.rast.list futures_series

g.gui.animation strds=futures_series